# TCL File Generated by Component Editor 20.1
# Mon Sep 07 22:16:25 CEST 2020
# DO NOT MODIFY


# 
# Huffman_coder_ip "Huffman_coder_comp" v2.0
#  2020.09.07.22:16:25
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Huffman_coder_ip
# 
set_module_property DESCRIPTION ""
set_module_property NAME Huffman_coder_ip
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP MyOwn
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Huffman_coder_comp
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Huffman_coder_rtl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Huffman_coder_rtl.v VERILOG PATH Huffman_coder_rtl.v TOP_LEVEL_FILE
add_fileset_file coder.v VERILOG PATH coder.v
add_fileset_file memory_unit.v VERILOG PATH memory_unit.v
add_fileset_file FIFO_coder.v VERILOG PATH FIFO_coder.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL Huffman_coder_rtl
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file Huffman_coder_rtl.v VERILOG PATH Huffman_coder_rtl.v
add_fileset_file coder.v VERILOG PATH coder.v
add_fileset_file memory_unit.v VERILOG PATH memory_unit.v
add_fileset_file FIFO_coder.v VERILOG PATH FIFO_coder.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock_sink
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset resetn reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset clock_reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitStates 1
set_interface_property avalon_slave_0 writeWaitTime 1
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 chipselect chipselect Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock clk Input 1


# 
# connection point con_finalize
# 
add_interface con_finalize conduit end
set_interface_property con_finalize associatedClock ""
set_interface_property con_finalize associatedReset ""
set_interface_property con_finalize ENABLED true
set_interface_property con_finalize EXPORT_OF ""
set_interface_property con_finalize PORT_NAME_MAP ""
set_interface_property con_finalize CMSIS_SVD_VARIABLES ""
set_interface_property con_finalize SVD_ADDRESS_GROUP ""

add_interface_port con_finalize finalize export Input 1


# 
# connection point con_empty
# 
add_interface con_empty conduit end
set_interface_property con_empty associatedClock ""
set_interface_property con_empty associatedReset ""
set_interface_property con_empty ENABLED true
set_interface_property con_empty EXPORT_OF ""
set_interface_property con_empty PORT_NAME_MAP ""
set_interface_property con_empty CMSIS_SVD_VARIABLES ""
set_interface_property con_empty SVD_ADDRESS_GROUP ""

add_interface_port con_empty empty_out export Output 1


# 
# connection point con_access_mode
# 
add_interface con_access_mode conduit end
set_interface_property con_access_mode associatedClock ""
set_interface_property con_access_mode associatedReset ""
set_interface_property con_access_mode ENABLED true
set_interface_property con_access_mode EXPORT_OF ""
set_interface_property con_access_mode PORT_NAME_MAP ""
set_interface_property con_access_mode CMSIS_SVD_VARIABLES ""
set_interface_property con_access_mode SVD_ADDRESS_GROUP ""

add_interface_port con_access_mode access_mode export Input 1

